# Generated by Django 5.1 on 2024-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, default='', null=True)),
                ('full_desc', models.TextField(blank=True, default='', null=True)),
                ('work_count', models.IntegerField(default=1)),
                ('images', models.ImageField(blank=True, null=True, upload_to='order_image/')),
                ('is_finish', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('success', 'Success'), ('cancel_client', 'Cancel by Client'), ('cancel_user', 'Cancel by User')], default='stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
