# Generated by Django 5.1 on 2024-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
