# Generated by Django 5.1 on 2024-09-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=10),
        ),
    ]
