# Generated by Django 5.1 on 2024-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_order_city_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
